# Generated by Django 4.2.1 on 2023-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.URLField(max_length=250, verbose_name='Ваша длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(max_length=250, unique=True, verbose_name='Готовая ваша сокращенная ссылка'),
        ),
    ]
